config/routes.rb
Rails.application.routes.draw do
  resources :users

  root 'users#index'

  get '/about' => 'users#about'

end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  protect_from_forgery

  def reset_rsvp
    User.update_all('status' => 'changed')
  end

  def index
    @users = User.all
    next_game
    @next_game_day_name = next_game_day_name
  end

  def new
  end

  def create
    @user = User.new
    @user.name = params[:user][:name]
    @user.save
    redirect_to edit_user_url(@user.id)
  end

  def edit
    @user = User.find(params[:id])
    next_game
    @next_game_day_name = next_game_day_name
  end

  def update
    @user = User.find(params[:id])
    if @user
      if params[:user][:name]
        @user.name = params[:user][:name]
      end
      if params[:user][:status]
        @user.status = params[:user][:status]
      end
      if params[:user][:email_address]
        @user.email_address = params[:user][:email_address]
      end
      @user.save
    end
    redirect_to users_url
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to users_url
  end

  def about
  end


  private

  def next_game
    # if Date.today.wday >= 1 && Date.today.wday <= 3
    #   @next_game = next_wednesday
    # else
      @next_game = next_sunday
    # end
  end

  def next_wednesday
    x = Date.today
    x += 1 until x.wday > 2 && x.wday < 4#for some reason, can't just use equal sign...
    x
  end

  def next_sunday
    x = Date.today
    x += 1 until x.wday <=0 #for some reason, can't just use equal sign
    x
  end

  def today?
    return true if @next_game == Date.today
  end

  def tomorrow?
    return true if @next_game == Date.today + 1
  end

  def next_game_day_name
    if today?
      'today'
    elsif tomorrow?
      'tomorrow'
    else
      "on #{Date::DAYNAMES[@next_game.wday]}"
    end
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Reed Basketball Attendance</title> <!check ch 3 of Hartl for dynamic title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <!take out following header class into partial? check tealeaf>
  <header class="navbar navbar-default">
      <div class="container">
        <nav>
          <ul class="nav navbar-nav navbar-left">
            <li><%= link_to 'Home', users_url %></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to 'About', about_url, class: 'btn btn-primary-outline' %></li>
          </ul>
        </nav>
      </div>
    </header>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <a class="navbar-brand" href="/">Tealeaf Todo</a>
    </div>
  </div>
</nav>

<header class="navbar navbar-default">
    <div class="container">
      <nav>
        <ul class="nav navbar-nav navbar-left">
          <li><%= link_to 'back',   '#' %></li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to 'about',   '#', class: 'btn btn-primary-outline' %></li>
        </ul>
      </nav>
    </div>
  </header>

app/views/users/about.html.erb
<h1> About </h1>

<h4>To Reed basketball players: </h4>
  This website serves to show Coach Ried and other players who is planning on
  coming to open gyms. Please note that all information is publicly viewable and
  may eventually show up in search engines (Google). Feel free to contact me
  (Matt '13) if you have any comments or questions!

<h4>To potential employers: </h4>
  Thank you for viewing my Rails site.

app/views/users/edit.html.erb
<h1> Reed College Basketball </h1>

<p> Hi <%= @user.name %>! Edit your status for the game
  <%=@next_game_day_name%> (<%=@next_game.strftime("%m/%d")%>) by selecting one
  of the buttons, or edit your username in the box below. Enter your email to
  receive prompts on Saturday to update your playing status.
</p>
<br>
<br>

<form action="/users/<%=@user.id%>" method='post'>
  <input type="hidden" name="_method" value="PATCH">
    <div class="btn-group" data-toggle="buttons">
      <% ['Yes', 'No', 'Maybe', 'NoResponse'].each do |option| %>
        <!for some reason, couldn't use :symbols for each loop, had to use string>
        <% if option == @user.status %>
          <label class="btn btn-default active">
          <input type="radio" name="user[status]" value="<%=option%>"
            checked> <%=option%>
        <% else %>
          <label class="btn btn-default">
          <input type="radio" name="user[status]" value="<%=option%>"> <%=option%>
        <% end %>
        </label>
      <% end %>
    </div>
    <br>
    <br>
  Username: <input type="text" name="user[name]" value="<%=@user.name%>">
  <br>
  Email: <input type="text" name="user[email_address]" value="<%=@user.email_address%>">
  <br>
  <br>
  <input type="submit" class='btn btn-default' value="Submit">
</form>

app/views/users/index.html.erb
<h1>Reed College Basketball</h1>

<p> Thank you for RSVPing before coming to Reed open gyms! Please click
  on your username to edit your status, or create a new user by clicking the
  button below.</p>

<br>
<%= link_to "Create new user", new_user_path, class: 'btn btn-default' %>
<br>
<br>
<br>

<h4> Open gym <%=@next_game_day_name%> (<%=@next_game.strftime("%m/%d")%>):</h4>

<div class="table-responsive">
  <table class = 'table table-hover'>
    <thead>
      <tr>
        <td> <h4> Username </h4> </td>
        <td> <h4> Status </h4> </td>
        <td> </td>
      </tr>
    </thead>

    <% if @users %>
      <% @users.each do |user| %>
        <tr>
          <td> <%= link_to "#{user.name}", edit_user_path(user.id),
            class: 'btn btn-default' %> </td>
          <td> <%= user.status %> </td>
          <td> <%= link_to "Delete", user_path(user.id), class: 'btn btn-default',
            method: :delete, data: {
              confirm: "Are you sure you want to delete #{user.name}?" } %> </td>
        </tr>
      <% end %>
    <% end %>

  </table>
</div>

app/views/users/new.html.erb
<h1> Reed College Basketball </h1>

<p> Enter your desired username in the box below. </p>

<form action="/users" method="post">
  <input type="text" name="user[name]">
  <br>
  <br>
  <input type="submit" value="Create new user" class='btn btn-default'>
</form>